name: gem build

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build_gem:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.7']
    outputs:
      app-perf-agent-gem-version: ${{ env.APP_PERF_GEM_VERSION }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: build gem
      run: |
        git clone https://github.com/infraoptics/app_perf_agent.git
        gem build app_perf_agent/app_perf_agent.gemspec
    - name: Set gem version
      run: echo "APP_PERF_GEM_VERSION=$(ls -t app_perf_agent*.gem | sed 's/.*-\([0-9\.][0-9\.]*\)\..*/\1/')" >> $GITHUB_ENV
    - uses: actions/upload-artifact@v2
      with:
        name: app_perf_agent-${{ env.APP_PERF_GEM_VERSION }}.gem
        path: ${{ github.workspace }}/app_perf_agent-${{ env.APP_PERF_GEM_VERSION }}.gem
  build_rpm:
    needs: build_gem
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'
        bundler-cache: true
    - uses: actions/download-artifact@v2
      with:
        name: app_perf_agent-${{ needs.build_gem.outputs.app-perf-agent-gem-version }}.gem
    - name: install gem2rpm
      run: gem install gem2rpm
    - name: build rpm spec file
      run: gem2rpm -t scl.spec app_perf_agent-${{ needs.build_gem.outputs.app-perf-agent-gem-version }}.gem > app_perf_agent-${{ needs.build_gem.outputs.app-perf-agent-gem-version }}.spec
    - uses: actions/upload-artifact@v2
      with:
        name: app_perf_agent-${{ needs.build_gem.outputs.app-perf-agent-gem-version }}.spec
        path: ${{ github.workspace }}
    - uses: mosteo-actions/docker-run@v1
      with:
        image: infraoptics/rpmbuild:centos7
        command: |
          bash -c "source scl_source enable rh-ruby27 && mkdir -p /root/rpmbuild/SOURCES/ && cp app_perf_agent-${{ needs.build_gem.outputs.app-perf-agent-gem-version }}.gem /root/rpmbuild/SOURCES/ && rpmbuild -bb app_perf_agent-${{ needs.build_gem.outputs.app-perf-agent-gem-version }}.spec --define 'scl_prefix_ruby rh-ruby27-' --define 'scl rh-ruby27' && cp /root/rpmbuild/RPMS/noarch/* ${{ github.workspace }}/"
    - uses: actions/upload-artifact@v2
      with:
        name: app_perf_agent-${{ needs.build_gem.outputs.app-perf-agent-gem-version }}-rpm
        path: ${{ github.workspace }}/*.rpm
