name: Ruby

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.7']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: build gem
      run: |
        gem install gem2rpm
        git clone https://github.com/infraoptics/app_perf_agent.git
        gem build app_perf_agent/app_perf_agent.gemspec
        ls -t app_perf_agent-*.gem | head -1 | xargs gem2rpm > app_perf.spec
    - uses: actions/upload-artifact@v2
      with:
        name: app_perf.spec
        path: app_perf.spec
